version: "3.8"
services: 
    gql-server:
        stdin_open: true
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "8080:8080"
        volumes: 
            - "app/node_modules"
            - "./:/app"